spring.application.name=demo
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Configurações de Login do Spring Security
spring.security.user.name=admin
spring.security.user.password=123456

# Nome do banco e onde ele será salvo (será criado um arquivo chamado banco_oficina.mv.db)
spring.datasource.url=jdbc:h2:file:./banco_oficina
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Permite que o Spring crie/atualize as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ativa o console do H2 para você testar no navegador (localhost:8080/h2-console)
spring.h2.console.enabled=true